# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: "Windows Latest"
            os: windows-latest

          - name: "Ubuntu Latest"
            os: ubuntu-latest

        linux_os: ["archlinux", "centos7", "ubuntu"]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}
      
      - name: Setup compose
        run: cd docker && docker-compose up -d kerberos rest

      - name: Build and run tests on Windows
        if: startsWith(matrix.config.os, 'windows')
        run: |
          cd docker && docker-compose up windows
          docker-compose run --rm windows "/run.ps1"
          $exitcode=$LASTEXITCODE
          docker-compose down
          exit $exitcode

      - name: Build and run tests on linux
        if: startsWith(matrix.config.os, 'ubuntu')
        run: |
          cd docker && docker-compose up ${{ matrix.linux_os }}
          docker-compose run --rm $1 "/run.sh"
          exitcode=$?
          docker-compose down
          exit $exitcode

